### ISSUE TITLE
Let us disable telefunc's auto type checking or better, use our own type checking function as middleware (incl. code)

### ISSUE THREAD

**Issue by 205g0** [brillout/telefunc#85] opened 2023-09-10 11:45 UTC
Why: https://github.com/brillout/telefunc/issues/84

Before I wrote, that using a ded val lib is boilerplate but it actually isn't too bad (see example below), our benefits => no double validation at run-time and no boilerplate in the function signature and the first line (const parse =....)

So, disabling the auto type-checking at RT would be some nice first step.

some.telefunc.ts
```ts
const someZodTypeDef = z.object({
    email: z.string().email(),
  }),

async function doSomething(
  payload: z.infer<ypeof someZodTypeDef>,
) {
  try {
    const parsed = someZodTypeDef.parse(payload)
    return parsed
  } catch (e) {
    console.error(e)
  }
}
```
on the client:
```ts
doSomething({ email: 'some@email.com })
```

**Comment by brillout** [comment] 2023-09-11 10:01
Duplicate of https://github.com/brillout/telefunc/issues/42.

**Closed by brillout** 2023-09-11 10:01 UTC
