### ISSUE TITLE
Bug reported in terminal (receiving 500 in client-side console)

### ISSUE THREAD

**Issue by timgent** [brillout/telefunc#61] opened 2023-02-09 02:57 UTC
Error: [telefunc@0.1.44][Bug] You stumbled upon a bug in Telefunc's source code. Reach out at https://github.com/brillout/telefunc/issues/new or https://discord.com/invite/3DYWwk4xRQ and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes Telefunc more robust. Debug info (this is for the Telefunc maintainers; you can ignore this): `{"telefuncFilePathAbsolute":"path_to_repo/app/happies/happies.telefunc.ts","dirFiles":["Happies.telefunc.ts","page.tsx"]}`.
    at assertCollocation (path_to_repo/node_modules/telefunc/dist/cjs/node/server/runTelefunc/assertNamingConvention.js:28:24)
    at assertNamingConvention (path_to_repo/node_modules/telefunc/dist/cjs/node/server/runTelefunc/assertNamingConvention.js:9:9)
    at path_to_repo/node_modules/telefunc/dist/cjs/node/server/runTelefunc/findTelefunction.js:23:65
    at findTelefunction (path_to_repo/node_modules/telefunc/dist/cjs/node/server/runTelefunc/findTelefunction.js:26:7)
    at runTelefunc_ (path_to_repo/node_modules/telefunc/dist/cjs/node/server/runTelefunc.js:87:70)
    at async runTelefunc (path_to_repo/node_modules/telefunc/dist/cjs/node/server/runTelefunc.js:38:16)
    at async telefunc (path_to_repo/node_modules/telefunc/dist/cjs/node/server/telefunc.js:11:26)
    at async telefuncMiddleware (webpack-internal:///(api)/./pages/api/_telefunc.ts:16:26)
    at async Object.apiResolver (path_to_repo/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (path_to_repo/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (path_to_repo/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (path_to_repo/node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (path_to_repo/node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (path_to_repo/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
    at async DevServer.handleRequest (path_to_repo/node_modules/next/dist/server/base-server.js:322:20)

**Comment by brillout** [comment] 2023-02-09 10:38
Let me have a look.

**Comment by brillout** [comment] 2023-02-09 10:46
If you reload your app, does the error go away? (I suspect the error to be temporary.)

**Comment by timgent** [comment] 2023-02-09 11:29
Thanks you are quite right, I now get:
```
Error: [telefunc@0.1.44][Wrong Usage] You don't seem to be using Telefunc with a supported stack. Reach out on GitHub or Discord.
```

I've pushed the repo up here:

https://github.com/timgent/happiness_tracker_nextjs/tree/add_telefunc

Maybe something to do with the version of nextjs I'm using, or that I'm using the experimental `/app` directory?

**Comment by brillout** [comment] 2023-02-09 11:38
Let me look.

**Comment by timgent** [comment] 2023-02-09 11:46
Thanks. Also noticed I sometimes am getting this in the logs too:
```
./node_modules/@brillout/vite-plugin-import-build/dist/loadBuild/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@brillout/vite-plugin-import-build/dist/loadBuild/index.js
./node_modules/@brillout/vite-plugin-import-build/loadBuild.js
./node_modules/telefunc/dist/cjs/node/vite/loadTelefuncFilesWithVite.js
./node_modules/telefunc/dist/cjs/node/server/runTelefunc/loadTelefuncFiles.js
./node_modules/telefunc/dist/cjs/node/server/runTelefunc.js
./node_modules/telefunc/dist/cjs/node/server/telefunc.js
./node_modules/telefunc/dist/cjs/node/server/index.js
./app/happies/happies.telefunc.ts
./app/happies/page.tsx
```

The place it is calling telefunc is on this page: http://localhost:3000/happies (click the button, then click the button in the modal)

**Comment by brillout** [comment] 2023-02-09 13:53
I updated the Next.js example to Next.js 13 and the CI doesn't repport any regression. So, yea, it's probably due to the experimental `/app` dir, although it does seem to support Webpack plugins &ndash; let me see what's going on.

**Comment by brillout** [comment] 2023-02-09 14:11
I can't reproduce `[telefunc][Wrong Usage] You don't seem to be using Telefunc with a supported stack.`.

It actually seems to work just fine with `/app`.

**Comment by brillout** [comment] 2023-02-09 16:07
The new release `0.1.45`  fixes all issues mentioned here.

Let me know if you get `[telefunc][Wrong Usage] You don't seem to be using Telefunc with a supported stack` again and provide a step-by-step reproduction (I couldn't reproduce this with `app/`). Closing in the meantime.

**Comment by brillout** [comment] 2023-02-09 16:29
Actually, I'm still getting `Critical dependency: the request of a dependency is an expression`. Let me fix this.

**Comment by brillout** [comment] 2023-02-09 17:45
Done `0.1.46`.

**Closed by brillout** 2023-02-09 17:45 UTC
Labels: Bug :boom:

**Comment by timgent** [comment] 2023-02-09 18:50
Nice one thanks! I can confirm that's all working for me now. Great library btw

**Comment by brillout** [comment] 2023-02-09 20:19
I'm glad you like. Btw. in case your company is up for it: https://github.com/sponsors/brillout.
